name: Build

on:
  push:
    branches:
      - develop
      - main
    paths:
      - 'latest/**'
      - 'official/**'
      - .github/workflows/build.yml
      - versions.json
  workflow_dispatch:

env:
  DOCKERHUB_REPOSITORY: ${{ github.repository_owner }}/ktools
  SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
  SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
  SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      latest: ${{ steps.set-matrix.outputs.latest }}
      official: ${{ steps.set-matrix.outputs.official }}
    steps:
      - name: Check out
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set matrix
        id: set-matrix
        run: |
          json="$(cat ./versions.json)"
          {
            echo "latest=$(jq -cM .latest <<< "$json")"
            echo "official=$(jq -cM .official <<< "$json")"
          } >> "$GITHUB_OUTPUT"

  official-build:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ${{ fromJSON(needs.prepare.outputs.official) }}
    steps:
      - name: Check out
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Send Slack notification
        uses: codedsolar/slack-action@59996e0967dce98cf0f76825cad94daa7e6d4936 # v1.4.0
        if: ${{ github.event_name != 'pull_request' }}
        id: slack
        with:
          fields: |
            {STATUS}
            {REF}
            ImageMagick version: ${{ matrix.image.imagemagick_version }}
            ktools version: ${{ matrix.image.version }}
          status: in-progress
      - name: Set up QEMU
        uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1 # v4.4.0
        with:
          image: tonistiigi/binfmt:qemu-v10.2.3-68
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1
      - name: Login to private registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ${{ secrets.PRIVATE_REGISTRY_HOST }}
          username: ${{ secrets.PRIVATE_REGISTRY_USERNAME }}
          password: ${{ secrets.PRIVATE_REGISTRY_PASSWORD }}
      - name: Build a Debian image
        uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7.4.0
        id: debian
        with:
          build-args: |
            IMAGEMAGICK_IMAGE_PREFIX=${{ matrix.image.imagemagick_legacy && 'legacy-' || '' }}
            IMAGEMAGICK_VERSION=${{ matrix.image.imagemagick_version }}
            KTOOLS_VERSION=${{ matrix.image.version }}
          cache-from: type=registry,ref=${{ secrets.PRIVATE_REGISTRY_HOST }}/ktools:cache-official-${{ matrix.image.version }}-debian
          cache-to: type=registry,ref=${{ secrets.PRIVATE_REGISTRY_HOST }}/ktools:cache-official-${{ matrix.image.version }}-debian,mode=max
          context: .
          file: ./official/debian/Dockerfile
          labels: maintainer=victor@popkov.me
          platforms: linux/amd64,linux/386
          provenance: false
          pull: true
          push: true
          sbom: false
          tags: |
            ${{ secrets.PRIVATE_REGISTRY_HOST }}/ktools:official-${{ matrix.image.version }}-debian
      - name: Build an Alpine image
        uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7.4.0
        id: alpine
        with:
          build-args: |
            IMAGEMAGICK_IMAGE_PREFIX=${{ matrix.image.imagemagick_legacy && 'legacy-' || '' }}
            IMAGEMAGICK_VERSION=${{ matrix.image.imagemagick_version }}
            KTOOLS_VERSION=${{ matrix.image.version }}
          cache-from: type=registry,ref=${{ secrets.PRIVATE_REGISTRY_HOST }}/ktools:cache-official-${{ matrix.image.version }}-alpine
          cache-to: type=registry,ref=${{ secrets.PRIVATE_REGISTRY_HOST }}/ktools:cache-official-${{ matrix.image.version }}-alpine,mode=max
          context: .
          file: ./official/alpine/Dockerfile
          labels: maintainer=victor@popkov.me
          platforms: linux/amd64,linux/386
          provenance: false
          pull: true
          push: true
          sbom: false
          tags: |
            ${{ secrets.PRIVATE_REGISTRY_HOST }}/ktools:official-${{ matrix.image.version }}-alpine
      - name: Update Slack notification
        uses: codedsolar/slack-action@59996e0967dce98cf0f76825cad94daa7e6d4936 # v1.4.0
        if: ${{ github.event_name != 'pull_request' && always() }}
        with:
          fields: |
            {STATUS}
            {REF}
            ImageMagick version: ${{ matrix.image.imagemagick_version }}
            ktools version: ${{ matrix.image.version }}
          status: ${{ job.status }}
          timestamp: ${{ steps.slack.outputs.slack-timestamp }}

  latest-build:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ${{ fromJSON(needs.prepare.outputs.latest) }}
    steps:
      - name: Check out
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Send Slack notification
        uses: codedsolar/slack-action@59996e0967dce98cf0f76825cad94daa7e6d4936 # v1.4.0
        if: ${{ github.event_name != 'pull_request' }}
        id: slack
        with:
          fields: |
            {STATUS}
            {REF}
            ImageMagick version: ${{ matrix.image.imagemagick_version }}
            ktools version: ${{ matrix.image.version }}
          status: in-progress
      - name: Set up QEMU
        uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1 # v4.4.0
        with:
          image: tonistiigi/binfmt:qemu-v10.2.3-68
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1
      - name: Login to private registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ${{ secrets.PRIVATE_REGISTRY_HOST }}
          username: ${{ secrets.PRIVATE_REGISTRY_USERNAME }}
          password: ${{ secrets.PRIVATE_REGISTRY_PASSWORD }}
      - name: Build a Debian image
        uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7.4.0
        id: debian
        with:
          build-args: |
            IMAGEMAGICK_IMAGE_PREFIX=${{ matrix.image.imagemagick_legacy && 'legacy-' || '' }}
            IMAGEMAGICK_VERSION=${{ matrix.image.imagemagick_version }}
            KTOOLS_VERSION=${{ matrix.image.version }}
          cache-from: type=registry,ref=${{ secrets.PRIVATE_REGISTRY_HOST }}/ktools:cache-${{ matrix.image.version }}-debian
          cache-to: type=registry,ref=${{ secrets.PRIVATE_REGISTRY_HOST }}/ktools:cache-${{ matrix.image.version }}-debian,mode=max
          context: .
          file: ./latest/debian/Dockerfile
          labels: maintainer=victor@popkov.me
          platforms: linux/amd64,linux/386
          provenance: false
          pull: true
          push: true
          sbom: false
          tags: |
            ${{ secrets.PRIVATE_REGISTRY_HOST }}/ktools:${{ matrix.image.version }}-debian
      - name: Build an Alpine image
        uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7.4.0
        id: alpine
        with:
          build-args: |
            IMAGEMAGICK_IMAGE_PREFIX=${{ matrix.image.imagemagick_legacy && 'legacy-' || '' }}
            IMAGEMAGICK_VERSION=${{ matrix.image.imagemagick_version }}
            KTOOLS_VERSION=${{ matrix.image.version }}
          cache-from: type=registry,ref=${{ secrets.PRIVATE_REGISTRY_HOST }}/ktools:cache-${{ matrix.image.version }}-alpine
          cache-to: type=registry,ref=${{ secrets.PRIVATE_REGISTRY_HOST }}/ktools:cache-${{ matrix.image.version }}-alpine,mode=max
          context: .
          file: ./latest/alpine/Dockerfile
          labels: maintainer=victor@popkov.me
          platforms: linux/amd64,linux/386
          provenance: false
          pull: true
          push: true
          sbom: false
          tags: |
            ${{ secrets.PRIVATE_REGISTRY_HOST }}/ktools:${{ matrix.image.version }}-alpine
      - name: Update Slack notification
        uses: codedsolar/slack-action@59996e0967dce98cf0f76825cad94daa7e6d4936 # v1.4.0
        if: ${{ github.event_name != 'pull_request' && always() }}
        with:
          fields: |
            {STATUS}
            {REF}
            ImageMagick version: ${{ matrix.image.imagemagick_version }}
            ktools version: ${{ matrix.image.version }}
          status: ${{ job.status }}
          timestamp: ${{ steps.slack.outputs.slack-timestamp }}

  official-push:
    needs: [prepare, official-build]
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    strategy:
      max-parallel: 1
      matrix:
        image: ${{ fromJSON(needs.prepare.outputs.official) }}
    steps:
      - name: Check out
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Send Slack notification
        uses: codedsolar/slack-action@59996e0967dce98cf0f76825cad94daa7e6d4936 # v1.4.0
        if: ${{ github.event_name != 'pull_request' }}
        id: slack
        with:
          fields: |
            {STATUS}
            {REF}
            ImageMagick version: ${{ matrix.image.imagemagick_version }}
            ktools version: ${{ matrix.image.version }}
          status: in-progress
      - name: Set up QEMU
        uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1 # v4.4.0
        with:
          image: tonistiigi/binfmt:qemu-v10.2.3-68
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1
      - name: Login to private registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ${{ secrets.PRIVATE_REGISTRY_HOST }}
          username: ${{ secrets.PRIVATE_REGISTRY_USERNAME }}
          password: ${{ secrets.PRIVATE_REGISTRY_PASSWORD }}
      - name: Login to Docker Hub
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GHCR
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Prepare Docker meta for a Debian image
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        id: debian-meta
        with:
          flavor: prefix=official-,onlatest=true
          images: |
            ${{ env.DOCKERHUB_REPOSITORY }}
            ghcr.io/${{ env.DOCKERHUB_REPOSITORY }}
          labels: maintainer=victor@popkov.me
          tags: |
            type=raw,value=${{ matrix.image.version }}-imagemagick-${{ matrix.image.imagemagick_version }}-debian
            type=raw,value=${{ matrix.image.version }}-debian
            type=raw,value=${{ matrix.image.version }}
            ${{ matrix.image.latest && 'type=raw,value=debian' || '' }}
      - name: Build a Debian image
        uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7.4.0
        with:
          build-args: |
            IMAGEMAGICK_IMAGE_PREFIX=${{ matrix.image.imagemagick_legacy && 'legacy-' || '' }}
            IMAGEMAGICK_VERSION=${{ matrix.image.imagemagick_version }}
            KTOOLS_VERSION=${{ matrix.image.version }}
          cache-from: type=registry,ref=${{ secrets.PRIVATE_REGISTRY_HOST }}/ktools:cache-official-${{ matrix.image.version }}-debian
          context: .
          file: ./official/debian/Dockerfile
          labels: ${{ steps.debian-meta.outputs.labels }}
          platforms: linux/amd64,linux/386
          provenance: false
          pull: true
          push: ${{ !env.ACT }}
          sbom: false
          tags: ${{ steps.debian-meta.outputs.tags }}
      - name: Prepare Docker meta for an Alpine image
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        id: alpine-meta
        with:
          images: |
            ${{ env.DOCKERHUB_REPOSITORY }}
            ghcr.io/${{ env.DOCKERHUB_REPOSITORY }}
          flavor: |
            latest=${{ matrix.image.latest || 'false' }}
            prefix=official-,onlatest=true
          labels: maintainer=victor@popkov.me
          tags: |
            type=raw,value=${{ matrix.image.version }}-imagemagick-${{ matrix.image.imagemagick_version }}-alpine
            type=raw,value=${{ matrix.image.version }}-alpine
            type=raw,value=${{ matrix.image.version }}
            ${{ matrix.image.latest && 'type=raw,value=alpine' || '' }}
            ${{ matrix.image.latest && 'type=raw,prefix=,value=official' || '' }}
      - name: Build an Alpine image
        uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7.4.0
        with:
          build-args: |
            IMAGEMAGICK_IMAGE_PREFIX=${{ matrix.image.imagemagick_legacy && 'legacy-' || '' }}
            IMAGEMAGICK_VERSION=${{ matrix.image.imagemagick_version }}
            KTOOLS_VERSION=${{ matrix.image.version }}
          cache-from: type=registry,ref=${{ secrets.PRIVATE_REGISTRY_HOST }}/ktools:cache-official-${{ matrix.image.version }}-alpine
          context: .
          file: ./official/alpine/Dockerfile
          labels: ${{ steps.alpine-meta.outputs.labels }}
          platforms: linux/amd64,linux/386
          provenance: false
          pull: true
          push: ${{ !env.ACT }}
          sbom: false
          tags: ${{ steps.alpine-meta.outputs.tags }}
      - name: Update Slack notification
        uses: codedsolar/slack-action@59996e0967dce98cf0f76825cad94daa7e6d4936 # v1.4.0
        if: ${{ github.event_name != 'pull_request' && always() }}
        with:
          fields: |
            {STATUS}
            {REF}
            ImageMagick version: ${{ matrix.image.imagemagick_version }}
            ktools version: ${{ matrix.image.version }}
          status: ${{ job.status }}
          timestamp: ${{ steps.slack.outputs.slack-timestamp }}

  latest-push:
    needs: [prepare, latest-build, official-push]
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    strategy:
      max-parallel: 1
      matrix:
        image: ${{ fromJSON(needs.prepare.outputs.latest) }}
    steps:
      - name: Check out
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Send Slack notification
        uses: codedsolar/slack-action@59996e0967dce98cf0f76825cad94daa7e6d4936 # v1.4.0
        if: ${{ github.event_name != 'pull_request' }}
        id: slack
        with:
          fields: |
            {STATUS}
            {REF}
            ImageMagick version: ${{ matrix.image.imagemagick_version }}
            ktools version: ${{ matrix.image.version }}
          status: in-progress
      - name: Set up QEMU
        uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1 # v4.4.0
        with:
          image: tonistiigi/binfmt:qemu-v10.2.3-68
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1
      - name: Login to private registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ${{ secrets.PRIVATE_REGISTRY_HOST }}
          username: ${{ secrets.PRIVATE_REGISTRY_USERNAME }}
          password: ${{ secrets.PRIVATE_REGISTRY_PASSWORD }}
      - name: Login to Docker Hub
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GHCR
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Prepare Docker meta for a Debian image
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        id: debian-meta
        with:
          images: |
            ${{ env.DOCKERHUB_REPOSITORY }}
            ghcr.io/${{ env.DOCKERHUB_REPOSITORY }}
          labels: maintainer=victor@popkov.me
          tags: |
            type=raw,value=${{ matrix.image.version }}-imagemagick-${{ matrix.image.imagemagick_version }}-debian
            type=raw,value=${{ matrix.image.version }}-debian
            type=raw,value=${{ matrix.image.version }}
            ${{ matrix.image.latest && 'type=raw,value=debian' || '' }}
      - name: Build a Debian image
        uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7.4.0
        with:
          build-args: |
            IMAGEMAGICK_IMAGE_PREFIX=${{ matrix.image.imagemagick_legacy && 'legacy-' || '' }}
            IMAGEMAGICK_VERSION=${{ matrix.image.imagemagick_version }}
            KTOOLS_VERSION=${{ matrix.image.version }}
          cache-from: type=registry,ref=${{ secrets.PRIVATE_REGISTRY_HOST }}/ktools:cache-${{ matrix.image.version }}-debian
          context: .
          file: ./latest/debian/Dockerfile
          labels: ${{ steps.debian-meta.outputs.labels }}
          platforms: linux/amd64,linux/386
          provenance: false
          pull: true
          push: ${{ !env.ACT }}
          sbom: false
          tags: ${{ steps.debian-meta.outputs.tags }}
      - name: Prepare Docker meta for an Alpine image
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        id: alpine-meta
        with:
          images: |
            ${{ env.DOCKERHUB_REPOSITORY }}
            ghcr.io/${{ env.DOCKERHUB_REPOSITORY }}
          flavor: latest=${{ matrix.image.latest || 'false' }}
          labels: maintainer=victor@popkov.me
          tags: |
            type=raw,value=${{ matrix.image.version }}-imagemagick-${{ matrix.image.imagemagick_version }}-alpine
            type=raw,value=${{ matrix.image.version }}-alpine
            type=raw,value=${{ matrix.image.version }}
            ${{ matrix.image.latest && 'type=raw,value=alpine' || '' }}
      - name: Build an Alpine image
        uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7.4.0
        with:
          build-args: |
            IMAGEMAGICK_IMAGE_PREFIX=${{ matrix.image.imagemagick_legacy && 'legacy-' || '' }}
            IMAGEMAGICK_VERSION=${{ matrix.image.imagemagick_version }}
            KTOOLS_VERSION=${{ matrix.image.version }}
          cache-from: type=registry,ref=${{ secrets.PRIVATE_REGISTRY_HOST }}/ktools:cache-${{ matrix.image.version }}-alpine
          context: .
          file: ./latest/alpine/Dockerfile
          labels: ${{ steps.alpine-meta.outputs.labels }}
          platforms: linux/amd64,linux/386
          provenance: false
          pull: true
          push: ${{ !env.ACT }}
          sbom: false
          tags: ${{ steps.alpine-meta.outputs.tags }}
      - name: Update Slack notification
        uses: codedsolar/slack-action@59996e0967dce98cf0f76825cad94daa7e6d4936 # v1.4.0
        if: ${{ github.event_name != 'pull_request' && always() }}
        with:
          fields: |
            {STATUS}
            {REF}
            ImageMagick version: ${{ matrix.image.imagemagick_version }}
            ktools version: ${{ matrix.image.version }}
          status: ${{ job.status }}
          timestamp: ${{ steps.slack.outputs.slack-timestamp }}
