name: CI

permissions:
  contents: read

concurrency:
  group: CI-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main
  workflow_dispatch:

env:
  SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
  SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
  SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Check out
        uses: actions/checkout@v5
      - name: Set matrix
        id: set-matrix
        run: |
          json="$(cat ./versions.json)"
          matrix="$(jq -cM '
            (
              [ .latest[] | { version: .version, family: "latest", imagemagick_version: .imagemagick_version, imagemagick_legacy: (.imagemagick_legacy // false), latest: (.latest // false) } ]
              +
              [ .official[] | { version: .version, family: "official", imagemagick_version: .imagemagick_version, imagemagick_legacy: (.imagemagick_legacy // false), latest: (.latest // false) } ]
            )
          ' <<< "$json")"
          echo "matrix=${matrix}" >> "$GITHUB_OUTPUT"

  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      docker: ${{ steps.filter.outputs.docker }}
    steps:
      - name: Check out
        uses: actions/checkout@v5
      - name: Check for docker-related changes
        uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            docker:
              - 'latest/**'
              - 'official/**'
              - 'tests/**'
              - '.github/workflows/ci.yml'
              - 'versions.json'

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v5
      - name: Set up Node.js
        uses: actions/setup-node@v6
        id: node
        with:
          node-version: 24.11.0
      - name: Send Slack notification
        uses: codedsolar/slack-action@v1
        if: ${{ github.event_name != 'pull_request' }}
        id: slack
        with:
          fields: |
            {STATUS}
            {REF}
            Node.js: ${{ steps.node.outputs.node-version }}
            Hadolint issues: Checking...
            Prettier issues: Checking...
            ShellCheck issues: Checking...
          status: in-progress
      - name: Enable corepack
        run: corepack enable
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint using Prettier
        run: pnpm exec prettier --check . || true
      - name: Output Prettier results
        id: prettier
        run: echo "issues=$(pnpm exec prettier --list-different . | wc -l)" >> "$GITHUB_OUTPUT"
      - name: Lint using Hadolint (latest Alpine)
        uses: hadolint/hadolint-action@v3.1.0
        id: hadolint-latest-alpine
        with:
          dockerfile: ./latest/alpine/Dockerfile
          no-fail: true
      - name: Lint using Hadolint (latest Debian)
        uses: hadolint/hadolint-action@v3.1.0
        id: hadolint-latest-debian
        with:
          dockerfile: ./latest/debian/Dockerfile
          no-fail: true
      - name: Lint using Hadolint (official Alpine)
        uses: hadolint/hadolint-action@v3.1.0
        id: hadolint-official-alpine
        with:
          dockerfile: ./official/alpine/Dockerfile
          no-fail: true
      - name: Lint using Hadolint (official Debian)
        uses: hadolint/hadolint-action@v3.1.0
        id: hadolint-official-debian
        with:
          dockerfile: ./official/debian/Dockerfile
          no-fail: true
      - name: Output Hadolint results
        id: hadolint
        run: |
          latest_alpine_issues="$(echo '${{ steps.hadolint-latest-alpine.outputs.results }}' | sed '/^$/d' | sed '$!N; /^\n$/D' | wc -l)"
          latest_debian_issues="$(echo '${{ steps.hadolint-latest-debian.outputs.results }}' | sed '/^$/d' | sed '$!N; /^\n$/D' | wc -l)"
          official_alpine_issues="$(echo '${{ steps.hadolint-official-alpine.outputs.results }}' | sed '/^$/d' | sed '$!N; /^\n$/D' | wc -l)"
          official_debian_issues="$(echo '${{ steps.hadolint-official-debian.outputs.results }}' | sed '/^$/d' | sed '$!N; /^\n$/D' | wc -l)"

          {
            echo "latest-alpine-issues=$latest_alpine_issues"
            echo "latest-debian-issues=$latest_debian_issues"
            echo "official-alpine-issues=$official_alpine_issues"
            echo "official-debian-issues=$official_debian_issues"
            echo "issues=$((latest_alpine_issues + latest_debian_issues + official_alpine_issues + official_debian_issues))"
          } >> "$GITHUB_OUTPUT"
      - name: Lint using ShellCheck
        run: pnpm lint:shellcheck || true
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Output ShellCheck results
        id: shellcheck
        run: echo "issues=$(pnpm exec shellcheck -f gcc bin/*.sh 2>&1 | wc -l)" >> "$GITHUB_OUTPUT"
      - name: Check results
        run: |
          hadolint_latest_alpine_issues="${{ steps.hadolint.outputs.latest-alpine-issues }}"
          hadolint_latest_debian_issues="${{ steps.hadolint.outputs.latest-debian-issues }}"
          hadolint_official_alpine_issues="${{ steps.hadolint.outputs.official-alpine-issues }}"
          hadolint_official_debian_issues="${{ steps.hadolint.outputs.official-debian-issues }}"
          hadolint_issues="${{ steps.hadolint.outputs.issues }}"
          prettier_issues="${{ steps.prettier.outputs.issues }}"
          shellcheck_issues="${{ steps.shellcheck.outputs.issues }}"

          echo "Hadolint issues (latest Alpine): $hadolint_latest_alpine_issues"
          echo "Hadolint issues (latest Debian): $hadolint_latest_debian_issues"
          echo "Hadolint issues (official Alpine): $hadolint_official_alpine_issues"
          echo "Hadolint issues (official Debian): $hadolint_official_debian_issues"
          echo "Total Hadolint issues: $hadolint_issues"
          echo "Total Prettier issues: $prettier_issues"
          echo "Total ShellCheck issues: $shellcheck_issues"

          exit_code=1
          if [ "$prettier_issues" = '0' ] && [ "$hadolint_issues" = '0' ] && [ "$shellcheck_issues" = '0' ]; then
            exit_code=0
          fi
          exit "$exit_code"
      - name: Update Slack notification
        uses: codedsolar/slack-action@v1
        if: ${{ github.event_name != 'pull_request' && always() }}
        with:
          fields: |
            {STATUS}
            {REF}
            Node.js: ${{ steps.node.outputs.node-version }}
            Hadolint issues: ${{ steps.hadolint.outputs.issues || 'Skipped' }}
            Prettier issues: ${{ steps.prettier.outputs.issues || 'Skipped' }}
            ShellCheck issues: ${{ steps.shellcheck.outputs.issues || 'Skipped' }}
          status: ${{ job.status }}
          timestamp: ${{ steps.slack.outputs.slack-timestamp }}

  build:
    needs: [changes, prepare]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || needs.changes.outputs.docker == 'true' }}
    strategy:
      matrix:
        image: ${{ fromJSON(needs.prepare.outputs.matrix) }}
    steps:
      - name: Check out
        uses: actions/checkout@v5
      - name: Send Slack notification
        uses: codedsolar/slack-action@v1
        if: ${{ github.event_name != 'pull_request' }}
        id: slack
        with:
          fields: |
            {STATUS}
            {REF}
            ImageMagick version: ${{ matrix.image.imagemagick_version }}
            ktools version: ${{ matrix.image.version }}
          status: in-progress
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build a Debian image
        uses: docker/build-push-action@v6
        with:
          build-args: |
            IMAGEMAGICK_IMAGE_PREFIX=${{ matrix.image.imagemagick_legacy && 'legacy-' || '' }}
            IMAGEMAGICK_VERSION=${{ matrix.image.imagemagick_version }}
            KTOOLS_VERSION=${{ matrix.image.version }}
          context: .
          file: ./${{ matrix.image.family }}/debian/Dockerfile
          labels: maintainer=victor@popkov.me
          load: true
          platforms: linux/amd64
          pull: true
          push: false
          tags: |
            ${{ matrix.image.family }}-${{ matrix.image.version }}-debian
      - name: Build an Alpine image
        uses: docker/build-push-action@v6
        with:
          build-args: |
            IMAGEMAGICK_IMAGE_PREFIX=${{ matrix.image.imagemagick_legacy && 'legacy-' || '' }}
            IMAGEMAGICK_VERSION=${{ matrix.image.imagemagick_version }}
            KTOOLS_VERSION=${{ matrix.image.version }}
          context: .
          file: ./${{ matrix.image.family }}/alpine/Dockerfile
          labels: maintainer=victor@popkov.me
          load: true
          platforms: linux/amd64
          pull: true
          push: false
          tags: |
            ${{ matrix.image.family }}-${{ matrix.image.version }}-alpine
      - name: Tag Alpine image
        if: ${{ matrix.image.latest }}
        run: docker tag ${{ matrix.image.family }}-${{ matrix.image.version }}-alpine ${{ matrix.image.family }}
      - name: Save Alpine image
        if: ${{ matrix.image.latest }}
        run: docker save -o ./ci-${{ matrix.image.family }}-alpine.tar ${{ matrix.image.family }}
      - name: Upload Alpine image
        if: ${{ matrix.image.latest }}
        uses: actions/upload-artifact@v4
        with:
          name: ci-${{ matrix.image.family }}-alpine-${{ github.run_id }}
          path: ci-${{ matrix.image.family }}-alpine.tar
          retention-days: 1
      - name: Update Slack notification
        uses: codedsolar/slack-action@v1
        if: ${{ github.event_name != 'pull_request' && always() }}
        with:
          fields: |
            {STATUS}
            {REF}
            ImageMagick version: ${{ matrix.image.imagemagick_version }}
            ktools version: ${{ matrix.image.version }}
          status: ${{ job.status }}
          timestamp: ${{ steps.slack.outputs.slack-timestamp }}

  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v5
      - name: Download latest image
        uses: actions/download-artifact@v4
        with:
          name: ci-latest-alpine-${{ github.run_id }}
      - name: Download official image
        uses: actions/download-artifact@v4
        with:
          name: ci-official-alpine-${{ github.run_id }}
      - name: Load latest image
        run: docker load -i ci-latest-alpine.tar
      - name: Load official image
        run: docker load -i ci-official-alpine.tar
      - name: Send Slack notification
        uses: codedsolar/slack-action@v1
        if: ${{ github.event_name != 'pull_request' }}
        id: slack
        with:
          fields: |
            {STATUS}
            {REF}
            Testing: Checking...
          status: in-progress
      - name: Run tests
        run: |
          # latest
          echo 'Testing latest image...'
          echo '---'
          docker run --name test-latest \
            --user root \
            -v './tests:/tests:rw' \
            -w /tests/ \
            latest \
            /bin/sh -c './tests.sh'
          mkdir -p ./tests-latest-results/
          docker cp test-latest:/tests/result/. ./tests-latest-results/
          docker rm test-latest
          echo '---'

          # official
          echo 'Testing official image...'
          echo '---'
          docker run --name test-official \
            --user root \
            -v './tests:/tests:rw' \
            -w /tests/ \
            official \
            /bin/sh -c './tests.sh'
          mkdir -p ./tests-official-results/
          docker cp test-official:/tests/result/. ./tests-official-results/
          docker rm test-official
      - name: Upload latest test results
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: tests-latest-results-${{ github.run_id }}
          path: ./tests-latest-results
          retention-days: 7
      - name: Upload official test results
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: tests-official-results-${{ github.run_id }}
          path: ./tests-official-results
          retention-days: 7
      - name: Update Slack notification
        uses: codedsolar/slack-action@v1
        if: ${{ github.event_name != 'pull_request' && always() }}
        with:
          fields: |
            {STATUS}
            {REF}
            Testing: Completed
          status: ${{ job.status }}
          timestamp: ${{ steps.slack.outputs.slack-timestamp }}
